# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: VanillaWeb CI with Maven

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'doc/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate Test Report
      run: mvn surefire-report:report  
    - name: Upload Junit Test Report
      uses: actions/upload-artifact@v2
      with:
        name: JUnitTests-Report
        path: target/site/surefire-report.html
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
    